<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.MxNik</groupId>
        <artifactId>ForceChess</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>engine</artifactId>

    <!-- Syzygy endgame tablebases -->
    <repositories>
        <repository>
            <id>github</id>
            <url>https://maven.pkg.github.com/Aircraft009/piazzolla</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.MxNik</groupId>
            <artifactId>util</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>

        <!-- DL4J -->
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-core</artifactId>
            <version>${dl4j.version}</version>
        </dependency>

        <!-- ND4J CPU -->
<!--        <dependency>-->
<!--            <groupId>org.nd4j</groupId>-->
<!--            <artifactId>nd4j-native-platform</artifactId>-->
<!--            <version>${dl4j.version}</version>-->
<!--        </dependency>-->

        <!-- ND4J CUDA -->
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-cuda-11.6-platform</artifactId>
            <version>${dl4j.version}</version>
        </dependency>

        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-ui</artifactId>
            <version>1.0.0-M2.1</version>
        </dependency>

        <!-- Tests -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- Syzygy endgame tablebases -->
        <dependency>
            <groupId>net.chesstango</groupId>
            <artifactId>piazzolla</artifactId>
            <version>1.1.3-SNAPSHOT</version>
        </dependency>
        <!--JSON parser -->
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20220924</version>
        </dependency>


    </dependencies>

    <build>
        <plugins>
            <!-- Compiler -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <release>${java.version}</release>
                    <debug>true</debug>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.5.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>

                        <configuration>
                            <filters>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/*.SF</exclude>
                                        <exclude>META-INF/*.DSA</exclude>
                                        <exclude>META-INF/*.RSA</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>org.mxnik.forcechess.Training.Train</mainClass>
                                </transformer>
                                    <!--needed for DL4J/ND4J-->
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                            </transformers>
                        </configuration>

                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>