#All saved Fen-Strings and the default 8x8 board, saved as a property with their names
#Fri Apr 03 18:36:27 CEST 2026
9x9=rnbqkqbnr/ppppppppp/9/9/9/9/9/PPPPPPPPP/RNBQKQBNR w 0 0 0 9
default=rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w 0 0 0 8
