#The Users Settings
#Sun Jun 07 11:36:30 CEST 2026
boardPositionFile=C\:\\Users\\cocon\\Documents\\programming\\School\\POS\\ForceChess/../boardsNBots/FenBoards.properties
botFiles=C\:\\Users\\cocon\\Documents\\programming\\School\\POS\\ForceChess/../boardsNBots/bots/
darkHighlight=0xadd8e6ff
darkMoved=0x008000ff
darkSquare=0x00008bff
default_bot=
fp16=false
gpu_cpu=false
lightHighlight=0xf5deb3ff
lightMoved=0x00ff00ff
lightSquare=0xffffffff
network_data=C\:\\Users\\cocon\\Documents\\programming\\School\\POS\\ForceChess/../boardsNBots/bots/networks/
samples=C\:\\Users\\cocon\\Documents\\programming\\School\\POS\\ForceChess/../boardsNBots/bots/sample_data/
savePath=C\:\\Users\\cocon\\Documents\\programming\\School\\POS\\ForceChess/../boardsNBots/
